#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan.Models.DBChamCong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cienco6")]
	public partial class DBChamCongDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuserinfo(userinfo instance);
    partial void Updateuserinfo(userinfo instance);
    partial void Deleteuserinfo(userinfo instance);
    partial void Insertcheckinout(checkinout instance);
    partial void Updatecheckinout(checkinout instance);
    partial void Deletecheckinout(checkinout instance);
    #endregion
		
		public DBChamCongDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBChamCongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<userinfo> userinfos
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		public System.Data.Linq.Table<checkinout> checkinouts
		{
			get
			{
				return this.GetTable<checkinout>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LayChamCongConThieuVeERP")]
		public ISingleResult<sp_LayChamCongConThieuVeERPResult> sp_LayChamCongConThieuVeERP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string maMayChamCong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string qSearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, maMayChamCong, qSearch, tuNgay, denNgay, thang, nam);
			return ((ISingleResult<sp_LayChamCongConThieuVeERPResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _badgenumber;
		
		private System.Nullable<int> _defaultdeptid;
		
		private string _name;
		
		private string _Password;
		
		private string _Card;
		
		private System.Nullable<int> _Privilege;
		
		private System.Nullable<int> _AccGroup;
		
		private string _TimeZones;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _street;
		
		private string _zip;
		
		private string _ophone;
		
		private string _FPHONE;
		
		private string _pager;
		
		private string _minzu;
		
		private string _title;
		
		private string _SN;
		
		private string _SSN;
		
		private System.Nullable<System.DateTime> _UTime;
		
		private string _State;
		
		private string _City;
		
		private System.Nullable<short> _SECURITYFLAGS;
		
		private short _DelTag;
		
		private System.Nullable<int> _RegisterOT;
		
		private System.Nullable<int> _AutoSchPlan;
		
		private System.Nullable<int> _MinAutoSchInterval;
		
		private System.Nullable<int> _Image_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnbadgenumberChanging(string value);
    partial void OnbadgenumberChanged();
    partial void OndefaultdeptidChanging(System.Nullable<int> value);
    partial void OndefaultdeptidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCardChanging(string value);
    partial void OnCardChanged();
    partial void OnPrivilegeChanging(System.Nullable<int> value);
    partial void OnPrivilegeChanged();
    partial void OnAccGroupChanging(System.Nullable<int> value);
    partial void OnAccGroupChanged();
    partial void OnTimeZonesChanging(string value);
    partial void OnTimeZonesChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnophoneChanging(string value);
    partial void OnophoneChanged();
    partial void OnFPHONEChanging(string value);
    partial void OnFPHONEChanged();
    partial void OnpagerChanging(string value);
    partial void OnpagerChanged();
    partial void OnminzuChanging(string value);
    partial void OnminzuChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnSNChanging(string value);
    partial void OnSNChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnUTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUTimeChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnSECURITYFLAGSChanging(System.Nullable<short> value);
    partial void OnSECURITYFLAGSChanged();
    partial void OnDelTagChanging(short value);
    partial void OnDelTagChanged();
    partial void OnRegisterOTChanging(System.Nullable<int> value);
    partial void OnRegisterOTChanged();
    partial void OnAutoSchPlanChanging(System.Nullable<int> value);
    partial void OnAutoSchPlanChanged();
    partial void OnMinAutoSchIntervalChanging(System.Nullable<int> value);
    partial void OnMinAutoSchIntervalChanged();
    partial void OnImage_idChanging(System.Nullable<int> value);
    partial void OnImage_idChanged();
    #endregion
		
		public userinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this.OnbadgenumberChanging(value);
					this.SendPropertyChanging();
					this._badgenumber = value;
					this.SendPropertyChanged("badgenumber");
					this.OnbadgenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultdeptid", DbType="Int")]
		public System.Nullable<int> defaultdeptid
		{
			get
			{
				return this._defaultdeptid;
			}
			set
			{
				if ((this._defaultdeptid != value))
				{
					this.OndefaultdeptidChanging(value);
					this.SendPropertyChanging();
					this._defaultdeptid = value;
					this.SendPropertyChanged("defaultdeptid");
					this.OndefaultdeptidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(40)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card", DbType="NVarChar(20)")]
		public string Card
		{
			get
			{
				return this._Card;
			}
			set
			{
				if ((this._Card != value))
				{
					this.OnCardChanging(value);
					this.SendPropertyChanging();
					this._Card = value;
					this.SendPropertyChanged("Card");
					this.OnCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Privilege", DbType="Int")]
		public System.Nullable<int> Privilege
		{
			get
			{
				return this._Privilege;
			}
			set
			{
				if ((this._Privilege != value))
				{
					this.OnPrivilegeChanging(value);
					this.SendPropertyChanging();
					this._Privilege = value;
					this.SendPropertyChanged("Privilege");
					this.OnPrivilegeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccGroup", DbType="Int")]
		public System.Nullable<int> AccGroup
		{
			get
			{
				return this._AccGroup;
			}
			set
			{
				if ((this._AccGroup != value))
				{
					this.OnAccGroupChanging(value);
					this.SendPropertyChanging();
					this._AccGroup = value;
					this.SendPropertyChanged("AccGroup");
					this.OnAccGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZones", DbType="NVarChar(20)")]
		public string TimeZones
		{
			get
			{
				return this._TimeZones;
			}
			set
			{
				if ((this._TimeZones != value))
				{
					this.OnTimeZonesChanging(value);
					this.SendPropertyChanging();
					this._TimeZones = value;
					this.SendPropertyChanged("TimeZones");
					this.OnTimeZonesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(2)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="NVarChar(40)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this.OnstreetChanging(value);
					this.SendPropertyChanging();
					this._street = value;
					this.SendPropertyChanged("street");
					this.OnstreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="NVarChar(6)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ophone", DbType="NVarChar(20)")]
		public string ophone
		{
			get
			{
				return this._ophone;
			}
			set
			{
				if ((this._ophone != value))
				{
					this.OnophoneChanging(value);
					this.SendPropertyChanging();
					this._ophone = value;
					this.SendPropertyChanged("ophone");
					this.OnophoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPHONE", DbType="NVarChar(20)")]
		public string FPHONE
		{
			get
			{
				return this._FPHONE;
			}
			set
			{
				if ((this._FPHONE != value))
				{
					this.OnFPHONEChanging(value);
					this.SendPropertyChanging();
					this._FPHONE = value;
					this.SendPropertyChanged("FPHONE");
					this.OnFPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pager", DbType="NVarChar(20)")]
		public string pager
		{
			get
			{
				return this._pager;
			}
			set
			{
				if ((this._pager != value))
				{
					this.OnpagerChanging(value);
					this.SendPropertyChanging();
					this._pager = value;
					this.SendPropertyChanged("pager");
					this.OnpagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minzu", DbType="NVarChar(8)")]
		public string minzu
		{
			get
			{
				return this._minzu;
			}
			set
			{
				if ((this._minzu != value))
				{
					this.OnminzuChanging(value);
					this.SendPropertyChanging();
					this._minzu = value;
					this.SendPropertyChanged("minzu");
					this.OnminzuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(20)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="NVarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this.OnSNChanging(value);
					this.SendPropertyChanging();
					this._SN = value;
					this.SendPropertyChanged("SN");
					this.OnSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="NVarChar(20)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UTime
		{
			get
			{
				return this._UTime;
			}
			set
			{
				if ((this._UTime != value))
				{
					this.OnUTimeChanging(value);
					this.SendPropertyChanging();
					this._UTime = value;
					this.SendPropertyChanged("UTime");
					this.OnUTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(2)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITYFLAGS", DbType="SmallInt")]
		public System.Nullable<short> SECURITYFLAGS
		{
			get
			{
				return this._SECURITYFLAGS;
			}
			set
			{
				if ((this._SECURITYFLAGS != value))
				{
					this.OnSECURITYFLAGSChanging(value);
					this.SendPropertyChanging();
					this._SECURITYFLAGS = value;
					this.SendPropertyChanged("SECURITYFLAGS");
					this.OnSECURITYFLAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelTag", DbType="SmallInt NOT NULL")]
		public short DelTag
		{
			get
			{
				return this._DelTag;
			}
			set
			{
				if ((this._DelTag != value))
				{
					this.OnDelTagChanging(value);
					this.SendPropertyChanging();
					this._DelTag = value;
					this.SendPropertyChanged("DelTag");
					this.OnDelTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterOT", DbType="Int")]
		public System.Nullable<int> RegisterOT
		{
			get
			{
				return this._RegisterOT;
			}
			set
			{
				if ((this._RegisterOT != value))
				{
					this.OnRegisterOTChanging(value);
					this.SendPropertyChanging();
					this._RegisterOT = value;
					this.SendPropertyChanged("RegisterOT");
					this.OnRegisterOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoSchPlan", DbType="Int")]
		public System.Nullable<int> AutoSchPlan
		{
			get
			{
				return this._AutoSchPlan;
			}
			set
			{
				if ((this._AutoSchPlan != value))
				{
					this.OnAutoSchPlanChanging(value);
					this.SendPropertyChanging();
					this._AutoSchPlan = value;
					this.SendPropertyChanged("AutoSchPlan");
					this.OnAutoSchPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinAutoSchInterval", DbType="Int")]
		public System.Nullable<int> MinAutoSchInterval
		{
			get
			{
				return this._MinAutoSchInterval;
			}
			set
			{
				if ((this._MinAutoSchInterval != value))
				{
					this.OnMinAutoSchIntervalChanging(value);
					this.SendPropertyChanging();
					this._MinAutoSchInterval = value;
					this.SendPropertyChanged("MinAutoSchInterval");
					this.OnMinAutoSchIntervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_id", DbType="Int")]
		public System.Nullable<int> Image_id
		{
			get
			{
				return this._Image_id;
			}
			set
			{
				if ((this._Image_id != value))
				{
					this.OnImage_idChanging(value);
					this.SendPropertyChanging();
					this._Image_id = value;
					this.SendPropertyChanged("Image_id");
					this.OnImage_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.checkinout")]
	public partial class checkinout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _userid;
		
		private System.Nullable<System.DateTime> _checktime;
		
		private string _checktype;
		
		private System.Nullable<int> _verifycode;
		
		private string _SN;
		
		private string _sensorid;
		
		private string _WorkCode;
		
		private string _Reserved;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnchecktimeChanging(System.Nullable<System.DateTime> value);
    partial void OnchecktimeChanged();
    partial void OnchecktypeChanging(string value);
    partial void OnchecktypeChanged();
    partial void OnverifycodeChanging(System.Nullable<int> value);
    partial void OnverifycodeChanged();
    partial void OnSNChanging(string value);
    partial void OnSNChanged();
    partial void OnsensoridChanging(string value);
    partial void OnsensoridChanged();
    partial void OnWorkCodeChanging(string value);
    partial void OnWorkCodeChanged();
    partial void OnReservedChanging(string value);
    partial void OnReservedChanged();
    #endregion
		
		public checkinout()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this.OnchecktimeChanging(value);
					this.SendPropertyChanging();
					this._checktime = value;
					this.SendPropertyChanged("checktime");
					this.OnchecktimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktype", DbType="NVarChar(20)")]
		public string checktype
		{
			get
			{
				return this._checktype;
			}
			set
			{
				if ((this._checktype != value))
				{
					this.OnchecktypeChanging(value);
					this.SendPropertyChanging();
					this._checktype = value;
					this.SendPropertyChanged("checktype");
					this.OnchecktypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifycode", DbType="Int")]
		public System.Nullable<int> verifycode
		{
			get
			{
				return this._verifycode;
			}
			set
			{
				if ((this._verifycode != value))
				{
					this.OnverifycodeChanging(value);
					this.SendPropertyChanging();
					this._verifycode = value;
					this.SendPropertyChanged("verifycode");
					this.OnverifycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="NVarChar(30)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this.OnSNChanging(value);
					this.SendPropertyChanging();
					this._SN = value;
					this.SendPropertyChanged("SN");
					this.OnSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sensorid", DbType="NVarChar(30)")]
		public string sensorid
		{
			get
			{
				return this._sensorid;
			}
			set
			{
				if ((this._sensorid != value))
				{
					this.OnsensoridChanging(value);
					this.SendPropertyChanging();
					this._sensorid = value;
					this.SendPropertyChanged("sensorid");
					this.OnsensoridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkCode", DbType="NVarChar(20)")]
		public string WorkCode
		{
			get
			{
				return this._WorkCode;
			}
			set
			{
				if ((this._WorkCode != value))
				{
					this.OnWorkCodeChanging(value);
					this.SendPropertyChanging();
					this._WorkCode = value;
					this.SendPropertyChanged("WorkCode");
					this.OnWorkCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved", DbType="NVarChar(20)")]
		public string Reserved
		{
			get
			{
				return this._Reserved;
			}
			set
			{
				if ((this._Reserved != value))
				{
					this.OnReservedChanging(value);
					this.SendPropertyChanging();
					this._Reserved = value;
					this.SendPropertyChanged("Reserved");
					this.OnReservedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_LayChamCongConThieuVeERPResult
	{
		
		private System.Nullable<int> _userid;
		
		private string _badgenumber;
		
		private string _SN;
		
		private System.Nullable<int> _idQuet;
		
		private System.Nullable<System.DateTime> _checktime;
		
		public sp_LayChamCongConThieuVeERPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_badgenumber", DbType="VarChar(20)")]
		public string badgenumber
		{
			get
			{
				return this._badgenumber;
			}
			set
			{
				if ((this._badgenumber != value))
				{
					this._badgenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(20)")]
		public string SN
		{
			get
			{
				return this._SN;
			}
			set
			{
				if ((this._SN != value))
				{
					this._SN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuet", DbType="Int")]
		public System.Nullable<int> idQuet
		{
			get
			{
				return this._idQuet;
			}
			set
			{
				if ((this._idQuet != value))
				{
					this._idQuet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checktime", DbType="DateTime")]
		public System.Nullable<System.DateTime> checktime
		{
			get
			{
				return this._checktime;
			}
			set
			{
				if ((this._checktime != value))
				{
					this._checktime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
